name: Swatho Strapi Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_DIR: terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # -------- Ensure Terraform State Bucket --------
      - name: Create S3 bucket if not exists
        run: |
          aws s3api head-bucket --bucket swatho-terraform-state 2>/dev/null || \
          aws s3 mb s3://swatho-terraform-state --region $AWS_REGION

      # -------- Terraform --------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve

      - name: Get ECR Repo URL
        id: ecr
        working-directory: ${{ env.TF_DIR }}
        run: |
          ECR_URL=$(terraform output -raw ecr_repository_url)
          echo "ecr_url=$ECR_URL" >> $GITHUB_OUTPUT

      # -------- Login to ECR --------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin ${{ steps.ecr.outputs.ecr_url }}

      # -------- Build Docker Image --------
      - name: Build Docker Image
        run: |
          docker build -t strapi-app ./strapi-app

      # -------- Tag Image --------
      - name: Tag Docker Image
        run: |
          docker tag strapi-app:latest ${{ steps.ecr.outputs.ecr_url }}:latest

      # -------- Push Image --------
      - name: Push Docker Image
        run: |
          docker push ${{ steps.ecr.outputs.ecr_url }}:latest
